//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25_Abril.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int ID_Aluno { get; set; }
        public int Turma_ID { get; set; }
        public int Conta_ID { get; set; }
        public string Numero { get; set; }
    
        public virtual Conta Conta { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
