//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25_Abril.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities25Abril : DbContext
    {
        public Entities25Abril()
            : base("name=Entities25Abril")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Ano> Ano { get; set; }
        public virtual DbSet<Arte> Arte { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Conta> Conta { get; set; }
        public virtual DbSet<Gosto> Gosto { get; set; }
        public virtual DbSet<Tipo_de_Arte> Tipo_de_Arte { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
    
        public virtual ObjectResult<Nullable<bool>> acptArte(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("acptArte", nomeParameter);
        }
    
        public virtual int addAluno(Nullable<int> conta, Nullable<int> turma, string numero)
        {
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var turmaParameter = turma.HasValue ?
                new ObjectParameter("turma", turma) :
                new ObjectParameter("turma", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addAluno", contaParameter, turmaParameter, numeroParameter);
        }
    
        public virtual int addAno(Nullable<int> ano)
        {
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addAno", anoParameter);
        }
    
        public virtual int addArte(string nome, string descricao, Nullable<int> conta, Nullable<int> tipo, string caminho)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("descricao", descricao) :
                new ObjectParameter("descricao", typeof(string));
    
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var caminhoParameter = caminho != null ?
                new ObjectParameter("Caminho", caminho) :
                new ObjectParameter("Caminho", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addArte", nomeParameter, descricaoParameter, contaParameter, tipoParameter, caminhoParameter);
        }
    
        public virtual int addComentario(string comentario, Nullable<System.DateTime> data, Nullable<int> conta, Nullable<int> arte)
        {
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var arteParameter = arte.HasValue ?
                new ObjectParameter("arte", arte) :
                new ObjectParameter("arte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addComentario", comentarioParameter, dataParameter, contaParameter, arteParameter);
        }
    
        public virtual int addConta(string nome, string email, string password, Nullable<bool> admin)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var adminParameter = admin.HasValue ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addConta", nomeParameter, emailParameter, passwordParameter, adminParameter);
        }
    
        public virtual int addGosto(Nullable<int> conta, Nullable<int> arte, Nullable<System.DateTime> data)
        {
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var arteParameter = arte.HasValue ?
                new ObjectParameter("arte", arte) :
                new ObjectParameter("arte", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addGosto", contaParameter, arteParameter, dataParameter);
        }
    
        public virtual int addTipoArte(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTipoArte", tipoParameter);
        }
    
        public virtual int addTurma(string nome, Nullable<int> ano)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTurma", nomeParameter, anoParameter);
        }
    
        public virtual int delAluno(Nullable<int> conta)
        {
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delAluno", contaParameter);
        }
    
        public virtual int delAno(Nullable<int> ano)
        {
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delAno", anoParameter);
        }
    
        public virtual int delArte(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delArte", nomeParameter);
        }
    
        public virtual int delComentario(string comentario, Nullable<System.DateTime> data, Nullable<int> conta, Nullable<int> arte)
        {
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var arteParameter = arte.HasValue ?
                new ObjectParameter("arte", arte) :
                new ObjectParameter("arte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delComentario", comentarioParameter, dataParameter, contaParameter, arteParameter);
        }
    
        public virtual int delConta(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delConta", nomeParameter);
        }
    
        public virtual int delGosto(Nullable<int> conta, Nullable<int> arte)
        {
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var arteParameter = arte.HasValue ?
                new ObjectParameter("arte", arte) :
                new ObjectParameter("arte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delGosto", contaParameter, arteParameter);
        }
    
        public virtual int delTipoArte(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTipoArte", tipoParameter);
        }
    
        public virtual int delTurma(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTurma", nomeParameter);
        }
    
        public virtual ObjectResult<getAlunos_Result> getAlunos(string turma)
        {
            var turmaParameter = turma != null ?
                new ObjectParameter("turma", turma) :
                new ObjectParameter("turma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAlunos_Result>("getAlunos", turmaParameter);
        }
    
        public virtual ObjectResult<getArtes_Result> getArtes(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getArtes_Result>("getArtes", nomeParameter);
        }
    
        public virtual ObjectResult<getArtesTipo_Result> getArtesTipo(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getArtesTipo_Result>("getArtesTipo", tipoParameter);
        }
    
        public virtual ObjectResult<getComentarios_Result> getComentarios(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComentarios_Result>("getComentarios", nomeParameter);
        }
    
        public virtual ObjectResult<getComentariosArte_Result> getComentariosArte(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComentariosArte_Result>("getComentariosArte", nomeParameter);
        }
    
        public virtual ObjectResult<getConta_Result> getConta(Nullable<int> conta)
        {
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getConta_Result>("getConta", contaParameter);
        }
    
        public virtual ObjectResult<getContaAlunos_Result> getContaAlunos(string turma)
        {
            var turmaParameter = turma != null ?
                new ObjectParameter("turma", turma) :
                new ObjectParameter("turma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getContaAlunos_Result>("getContaAlunos", turmaParameter);
        }
    
        public virtual ObjectResult<getGostos_Result> getGostos(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGostos_Result>("getGostos", nomeParameter);
        }
    
        public virtual ObjectResult<getGostosArte_Result> getGostosArte(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGostosArte_Result>("getGostosArte", nomeParameter);
        }
    
        public virtual ObjectResult<getOrderComentarios_Result> getOrderComentarios(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getOrderComentarios_Result>("getOrderComentarios", nomeParameter);
        }
    
        public virtual ObjectResult<getRfvArtes_Result> getRfvArtes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRfvArtes_Result>("getRfvArtes");
        }
    
        public virtual ObjectResult<getRvfComentarios_Result> getRvfComentarios(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRvfComentarios_Result>("getRvfComentarios", nomeParameter);
        }
    
        public virtual ObjectResult<string> getTipoArtes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getTipoArtes");
        }
    
        public virtual ObjectResult<getTurmas_Result> getTurmas(Nullable<int> ano)
        {
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTurmas_Result>("getTurmas", anoParameter);
        }
    
        public virtual int rfvArte(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rfvArte", nomeParameter);
        }
    
        public virtual int rmvAdm(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rmvAdm", nomeParameter);
        }
    
        public virtual int stAdm(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stAdm", nomeParameter);
        }
    
        public virtual int updAluno(Nullable<int> conta, Nullable<int> nEWconta, Nullable<int> turma)
        {
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var nEWcontaParameter = nEWconta.HasValue ?
                new ObjectParameter("NEWconta", nEWconta) :
                new ObjectParameter("NEWconta", typeof(int));
    
            var turmaParameter = turma.HasValue ?
                new ObjectParameter("turma", turma) :
                new ObjectParameter("turma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updAluno", contaParameter, nEWcontaParameter, turmaParameter);
        }
    
        public virtual int updAno(Nullable<int> ano, Nullable<int> nEWano)
        {
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var nEWanoParameter = nEWano.HasValue ?
                new ObjectParameter("NEWano", nEWano) :
                new ObjectParameter("NEWano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updAno", anoParameter, nEWanoParameter);
        }
    
        public virtual int updArte(string nome, string newNome, string descricao, Nullable<int> conta, Nullable<int> tipo)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var newNomeParameter = newNome != null ?
                new ObjectParameter("newNome", newNome) :
                new ObjectParameter("newNome", typeof(string));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("descricao", descricao) :
                new ObjectParameter("descricao", typeof(string));
    
            var contaParameter = conta.HasValue ?
                new ObjectParameter("conta", conta) :
                new ObjectParameter("conta", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updArte", nomeParameter, newNomeParameter, descricaoParameter, contaParameter, tipoParameter);
        }
    
        public virtual int updConta(string nome, string newNome, string email, string password)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var newNomeParameter = newNome != null ?
                new ObjectParameter("newNome", newNome) :
                new ObjectParameter("newNome", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updConta", nomeParameter, newNomeParameter, emailParameter, passwordParameter);
        }
    
        public virtual int updTipoArte(string tipo, string @new)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var newParameter = @new != null ?
                new ObjectParameter("new", @new) :
                new ObjectParameter("new", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updTipoArte", tipoParameter, newParameter);
        }
    
        public virtual int updTurma(string nome, string nEWnome, Nullable<int> ano)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var nEWnomeParameter = nEWnome != null ?
                new ObjectParameter("NEWnome", nEWnome) :
                new ObjectParameter("NEWnome", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updTurma", nomeParameter, nEWnomeParameter, anoParameter);
        }
    }
}
