//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25_Abril.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosAdmin
    {
        public int ID_Pedido { get; set; }
        public int Conta_ID { get; set; }
        public string Imagem { get; set; }
        public string Titulo { get; set; }
        public int Status { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
